apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictor
  namespace: mlops
spec:
  replicas: 1
  selector: {matchLabels: {app: predictor}}
  template:
    metadata: {labels: {app: predictor}}
    spec:
      containers:
      - name: predictor
        image: yakhtenny/mlops:fastapi 
        imagePullPolicy: IfNotPresent
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow:5000"
        - name: AWS_ACCESS_KEY_ID
          valueFrom: { secretKeyRef: { name: minio-credentials, key: MINIO_ROOT_USER } }
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom: { secretKeyRef: { name: minio-credentials, key: MINIO_ROOT_PASSWORD } }
        - name: AWS_ENDPOINT_URL
          value: "http://minio:9000"
        ports: [{containerPort: 8080}]

---
apiVersion: v1
kind: Service
metadata:
  name: predictor
  namespace: mlops
spec:
  type: ClusterIP
  ports: [{port: 8080, targetPort: 8080}]
  selector: {app: predictor}
