apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ml-metrics-exporter.yaml
  - collector.yaml
  - prometheus-rules-monitor.yaml
  - evidently.yaml

helmCharts:
  - name: loki-stack
    repo: https://grafana.github.io/helm-charts
    version: 2.9.10
    releaseName: loki
    namespace: monitoring
    valuesFile: loki-helm-values.yaml
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 45.7.1
    releaseName: prometheus
    namespace: monitoring
    valuesFile: prometheus-helm-values.yaml
