apiVersion: v1
kind: ServiceAccount
metadata:
  name: kserve-sa     
  namespace: kubeflow
secrets:
- name: kserve-minio-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default-editor
  namespace: kubeflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeflow-default-editor-admin
subjects:
- kind: ServiceAccount
  name: default-editor
  namespace: kubeflow
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io