apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: strimzi

helmCharts:
  - name: strimzi-kafka-operator
    repo: https://strimzi.io/charts
    version: 0.41.0
    releaseName: strimzi
    namespace: strimzi-system

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: seldon

helmCharts:
  - name: seldon-core-v2
    repo: https://seldonio.github.io/helm-charts
    version: 2.11.0
    releaseName: seldon-system
    namespace: seldon-system

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kserve

helmCharts:
  - name: kserve
    repo: https://kserve.github.io/charts
    version: 0.11.0
    releaseName: kserve
    namespace: kserve
