apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/infrastructure
  - ../../base/kubeflow
  - ../../base/monitoring
  - ../../base/serving

commonLabels:
  env: dev
  platform: mlops
